from fastapi import APIRouter
from ..Tables import create_ai_task, get_ai_tasks #we import the functions related to tasks
from pydantic import BaseModel

#CREATION of AITASK (where the steps are generated by an external AI) endpoint
#USE GET(FrontEnd will send a request to GET data from Supabase)
#USE POsT(FrontEnd will send a request to POST data to Supabase)


ai_task_router = APIRouter()

class RequestAiTasks(BaseModel):
    goal_id: str
    title: str
    description: str
    due_date: str | None = None #either a due_date OR NOT
    ai_generated: bool

@ai_task_router.post("/ai_tasks")
def generate_ai_task(task: RequestAiTasks):
    result = create_ai_task(
        goal_id = task.goal_id,
        title = task.title,
        description = task.description,
        due_date = task.due_date,
        
    )
    return {
        "message": "AI task generated successfully",
        "task": result.data,
        "ai generated" : True 
    }

@ai_task_router.get("/ai-tasks/{goal_id}") #FETCH by goal_id!
def read_ai_tasks(goal_id: str):
    all_tasks = get_ai_tasks(goal_id) #search by goal id!
    
    if not all_tasks: #if goal has no tasks
        return {
            "tasks": [], 
            "message": "No tasks associated with this goal",  
        }

#not sure if this is nessacary as might be done through the table 
# # Filter for AI-generated tasks
#     ai_tasks = []
#     for task in all_tasks:
#         # Check if task is AI-generated (assuming task has 'ai_generated' field)
#         if task.get('ai_generated'):
#             ai_tasks.append(task)
    
#     if not ai_tasks:
#         return {
#             "tasks": [], 
#             "message": "No AI-generated tasks for this goal",
#         }
    
#     return {
#         "tasks": ai_tasks,
#         "message": f"Found {len(ai_tasks)} AI-generated tasks",
#         "ai_tasks_count": len(ai_tasks)
#     }