from fastapi import APIRouter
from ..Tables import create_task, get_tasks #we import the functions related to tasks
from pydantic import BaseModel

#CREATION of AITASK (where the steps are generated by an external AI) endpoint
#USE GET(FrontEnd will send a request to GET data from Supabase)
#USE POsT(FrontEnd will send a request to POST data to Supabase)


ai_task_router = APIRouter()

class RequestAiTasks(BaseModel):
    goal_id: str
    title: str
    description: str
    due_date: str | None = None #either a due_date OR NOT
    ai_created: bool

@ai_task_router.post("/ai_tasks")
def create_ai_task(task: RequestAiTasks):
    result = create_task(
        goal_id = task.goal_id,
        title = task.title,
        description = task.description,
        due_date = task.due_date,
        
    )
    return {
        "message": "AI task generated successfully",
        "task": result.data,
        "ai_created" : True 
    }

@ai_task_router.get("/ai_tasks/{goal_id}")
def read_ai_tasks(goal_id: str):
    all_ai_tasks = get_tasks(goal_id) #search by goal id!
    if not all_ai_tasks: #if user has no tasks, no tasks found for a specific user
        return {"tasks": [], "message": "No tasks assocciated with the user"}
    return {"tasks": all_ai_tasks}