from pydantic import BaseModel, Field, field_validator, ConfigDict
from typing import Optional, Any
from datetime import datetime
from enum import Enum
import uuid


# =============================================================================
# ENUMS
# =============================================================================

class TaskStatus(str, Enum):
    """
    Possible statuses for a task or subtask.
    Using an enum means FastAPI will reject any status that isn't one of these.
    """
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"


# =============================================================================
# TASK & SUBTASK SCHEMAS
# =============================================================================
#
# Two IDs per task — see Tables.py header comment for full explanation.
#   ai_id: Simple ID from AI (e.g., "task_1", "task_3a") — always present
#   id: UUID from backend — None until saved to database
#
# =============================================================================

class SubTask(BaseModel):
    """
    A subtask belonging to a parent task.
    
    Subtasks are simpler than tasks — no requires_input, no nested subtasks.
    They're just ordered steps within a task.
    
    Example:
        {
            "ai_id": "task_3a",
            "id": "a1b2c3d4-...",     ← None before saving to DB
            "description": "Inflate the tube slightly",
            "order": 1,
            "status": "not_started"
        }
    """
    ai_id: str = Field(
        ...,
        description="Simple AI-generated ID for tracking (e.g., 'task_3a')"
    )
    id: Optional[str] = Field(
        default=None,
        description="UUID — generated by backend when saved to DB. None before that."
    )
    description: str = Field(
        ...,
        description="What the user needs to do for this subtask"
    )
    order: int = Field(
        ...,
        description="Position within parent task's subtask list (1-indexed)"
    )
    status: TaskStatus = Field(
        default=TaskStatus.NOT_STARTED,
        description="Current status of the subtask"
    )
    
    model_config = ConfigDict(extra="forbid")

    @field_validator('ai_id')
    @classmethod
    def validate_ai_id(cls, v: str) -> str:
        """Make sure ai_id isn't empty or just whitespace."""
        if not v or len(v.strip()) == 0:
            raise ValueError("ai_id cannot be empty")
        return v.strip()


class Task(BaseModel):
    """
    A top-level task in a goal's ordered task list.
    
    Tasks are the main steps the user follows to achieve their goal.
    Each task can optionally contain subtasks for more granular steps.
    
    Example:
        {
            "ai_id": "task_3",
            "id": "550e8400-...",          ← None before saving to DB
            "description": "Find the puncture",
            "order": 3,
            "status": "not_started",
            "requires_input": false,
            "subtasks": [
                {"ai_id": "task_3a", "description": "Inflate tube", "order": 1, ...},
                {"ai_id": "task_3b", "description": "Check for bubbles", "order": 2, ...}
            ]
        }
    """
    ai_id: str = Field(
        ...,
        description="Simple AI-generated ID for tracking (e.g., 'task_1')"
    )
    id: Optional[str] = Field(
        default=None,
        description="UUID — generated by backend when saved to DB. None before that."
    )
    description: str = Field(
        ...,
        description="What the user needs to do for this task"
    )
    order: int = Field(
        ...,
        description="Position in the goal's task list (1-indexed)"
    )
    status: TaskStatus = Field(
        default=TaskStatus.NOT_STARTED,
        description="Current status of the task"
    )
    requires_input: bool = Field(
        default=False,
        description="If true, this task needs user input before AI can plan further. "
                    "E.g., 'Check eligibility requirements' — user must report back."
    )
    subtasks: list[SubTask] = Field(
        default_factory=list,
        description="Ordered list of subtasks (can be empty if not expanded yet)"
    )

    model_config = ConfigDict(extra="forbid")

    @field_validator('ai_id')
    @classmethod
    def validate_ai_id(cls, v: str) -> str:
        if not v or len(v.strip()) == 0:
            raise ValueError("ai_id cannot be empty")
        return v.strip()


# =============================================================================
# GOAL SCHEMA
# =============================================================================

class GoalData(BaseModel):
    """
    The complete goal structure stored as JSON in the database.
    
    This is what gets saved in the goals.goal_data JSONB column.
    Simple model: a goal has a title and an ordered list of tasks.
    No graph, no edges, no dependencies — just a flat ordered list
    where each task can have subtasks.
    
    Example of what goal_data looks like in the DB:
        {
            "goal_id": "550e8400-...",
            "user_id": "user_abc",
            "title": "Fix my bike tyre",
            "tasks": [
                {"ai_id": "task_1", "id": "...", "description": "Remove wheel", ...},
                {"ai_id": "task_2", "id": "...", "description": "Take out tube", ...}
            ]
        }
    """
    goal_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for the goal"
    )
    user_id: str = Field(
        ...,
        description="ID of the user who owns this goal"
    )
    title: str = Field(
        ...,
        description="The user's original goal input (e.g., 'Fix my bike tyre')"
    )
    tasks: list[Task] = Field(
        default_factory=list,
        description="Ordered list of tasks for this goal"
    )
    created_at: Optional[datetime] = Field(
        default_factory=datetime.utcnow
    )
    updated_at: Optional[datetime] = Field(
        default_factory=datetime.utcnow
    )

    model_config = ConfigDict(extra="forbid")

    # -------------------------------------------------------------------------
    # Helper methods — useful for backend logic without querying DB again
    # -------------------------------------------------------------------------

    def get_task_by_id(self, task_id: str) -> Optional[Task]:
        """Find a task by its UUID."""
        for task in self.tasks:
            if task.id == task_id:
                return task
        return None

    def get_task_by_ai_id(self, ai_id: str) -> Optional[Task]:
        """Find a task by its AI-generated ID (e.g., 'task_3')."""
        for task in self.tasks:
            if task.ai_id == ai_id:
                return task
        return None

    def get_subtask_by_id(self, subtask_id: str) -> Optional[tuple[Task, SubTask]]:
        """
        Find a subtask by its UUID.
        Returns (parent_task, subtask) tuple, or None if not found.
        """
        for task in self.tasks:
            for sub in task.subtasks:
                if sub.id == subtask_id:
                    return (task, sub)
        return None

    def get_completed_count(self) -> int:
        """Count all completed tasks and subtasks."""
        count = 0
        for task in self.tasks:
            if task.status == TaskStatus.COMPLETED:
                count += 1
            for sub in task.subtasks:
                if sub.status == TaskStatus.COMPLETED:
                    count += 1
        return count

    def get_total_count(self) -> int:
        """Count all tasks and subtasks (for progress like '3/7 done')."""
        count = 0
        for task in self.tasks:
            count += 1
            count += len(task.subtasks)
        return count

    def is_complete(self) -> bool:
        """Check if every task and subtask is completed."""
        for task in self.tasks:
            if task.status != TaskStatus.COMPLETED:
                return False
            for sub in task.subtasks:
                if sub.status != TaskStatus.COMPLETED:
                    return False
        return True


# =============================================================================
# AI RESPONSE SCHEMAS
# =============================================================================
#
# These define what we expect back from AI (or from our mock files).
# For MVP, mock_ai_responses.py returns data matching these shapes.
# When we integrate real AI later, we'll validate AI output against these.
#
# =============================================================================

class AIGeneratePlanResponse(BaseModel):
    """
    What AI returns when generating a plan for a new goal.
    
    Just a list of tasks with ai_ids. No UUIDs — backend adds those on save.
    """
    tasks: list[Task] = Field(
        ...,
        description="Ordered list of generated tasks",
        min_length=1  # AI must return at least one task
    )

    model_config = ConfigDict(extra="forbid")


class AIFeedbackResponse(BaseModel):
    """
    What AI returns after user gives feedback on a plan.
    
    AI returns the FULL updated task list (not just the changes).
    It preserves ai_ids for unchanged tasks and creates new ai_ids
    for brand new tasks. Backend uses ai_id matching to preserve UUIDs.
    """
    tasks: list[Task] = Field(
        ...,
        description="Full updated task list after incorporating feedback",
        min_length=1
    )

    model_config = ConfigDict(extra="forbid")


class AIExpandTaskResponse(BaseModel):
    """
    What AI returns when expanding a task into subtasks.
    
    Used when a user finds a task too hard and wants it broken down
    into smaller, more achievable steps.
    """
    task_ai_id: str = Field(
        ...,
        description="ai_id of the task being expanded (e.g., 'task_5')"
    )
    subtasks: list[SubTask] = Field(
        ...,
        description="New subtasks to add under the parent task",
        min_length=1
    )

    model_config = ConfigDict(extra="forbid")


# =============================================================================
# REQUEST SCHEMAS (what frontend sends to our endpoints)
# =============================================================================
#
# FastAPI automatically validates request bodies against these.
# If frontend sends bad data, FastAPI returns a 422 error with details.
#
# =============================================================================

class CreateGoalRequest(BaseModel):
    """
    Request body for POST /goals/
    
    Frontend sends just the goal title. Backend calls AI (or mock)
    to generate the task plan.
    
    Example: {"title": "Fix my bike tyre"}
    """
    title: str = Field(
        ...,
        description="The user's goal (e.g., 'Fix my bike tyre')"
    )


class FeedbackRequest(BaseModel):
    """
    Request body for POST /goals/{goal_id}/feedback
    
    User's free-text feedback about the plan. Can be used both
    on the review screen (before save) and after the goal is active.
    
    Example: {"feedback": "I don't like task_3, use soapy water instead"}
    """
    feedback: str = Field(
        ...,
        description="User's feedback on the plan"
    )


class ExpandTaskRequest(BaseModel):
    """
    Request body for POST /tasks/{task_id}/expand
    
    Sent when user clicks "expand" or "I'm stuck" on a specific task.
    The stuck_reason is optional — user can explain why they're stuck
    so AI can tailor the subtask breakdown.
    
    Example: {"task_id": "550e8400-...", "stuck_reason": "I don't have the right tools"}
    """
    task_id: str = Field(
        ...,
        description="UUID of the task to expand into subtasks"
    )
    stuck_reason: Optional[str] = Field(
        default=None,
        description="Optional: why the user is stuck (helps AI break it down better)"
    )


class UpdateTaskStatusRequest(BaseModel):
    """
    Request body for PATCH /tasks/{task_id}/status
    
    Used when user ticks a task as done or marks it in-progress.
    
    Example: {"status": "completed"}
    """
    status: TaskStatus = Field(
        ...,
        description="New status: 'not_started', 'in_progress', or 'completed'"
    )